/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI_1_2_JAVA_Swing;

import java.awt.Color;

/**
 *
 * @author DungNAPC
 */
public class S2_JFrameButton extends javax.swing.JFrame {

    /**
     * Creates new form S2_JFrameButton
     */
    public S2_JFrameButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_text = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        btn_Black = new javax.swing.JButton();
        btn_Red = new javax.swing.JButton();
        btn_Green = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_text.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_text.setText("jLabel1");

        btn_ok.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        btn_Black.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Black.setText("BLACK");
        btn_Black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BlackActionPerformed(evt);
            }
        });

        btn_Red.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Red.setText("RED");
        btn_Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RedActionPerformed(evt);
            }
        });

        btn_Green.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Green.setText("GREEN");
        btn_Green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btn_ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                        .addComponent(btn_Green))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lbl_text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Red, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Black, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lbl_text))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_Red)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Black)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btn_ok))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_Green)))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        System.out.println("Nút đã bấm rồi nè");
        //Gán giá trị cho Label và khi thực hiện hành động bấm nút thì sẽ set text lại
        lbl_text.setText("Chào mừng các bạn đến với JAVA 2");
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_BlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BlackActionPerformed
        lbl_text.setText("Bạn vừa bấm đổi mầu nền BLACK");
        this.getContentPane().setBackground(Color.BLACK);
    }//GEN-LAST:event_btn_BlackActionPerformed

    private void btn_RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RedActionPerformed
        lbl_text.setText("Bạn vừa bấm đổi mầu nền Red");
        this.getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_btn_RedActionPerformed

    private void btn_GreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GreenActionPerformed
        lbl_text.setText("Bạn vừa bấm đổi mầu nền GREEN");
        this.getContentPane().setBackground(Color.GREEN);
    }//GEN-LAST:event_btn_GreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S2_JFrameButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Black;
    private javax.swing.JButton btn_Green;
    private javax.swing.JButton btn_Red;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel lbl_text;
    // End of variables declaration//GEN-END:variables
}
